version: "3.7"

services:
  nginx:
    build:
      context: web-app
      dockerfile: nginx.Dockerfile
      args:
        fpm_host: fpm # 本番では、127.0.0.1に変更したイメージをビルド
    image: ecs-demo-nginx
    hostname: nginx
    container_name: container-demo-nginx
    ports:
      - "8080:80"
    depends_on:
      - fpm

  fpm:
    build:
      context: web-app
      dockerfile: fpm.Dockerfile
    image: ecs-demo-php-fpm
    hostname: fpm
    container_name: container-demo-fpm
    volumes:
      - ./web-app:/var/www
    environment:
      AWS_ACCESS_KEY_ID: local # 初期化
      AWS_SECRET_ACCESS_KEY: local # 初期化
    depends_on:
      - db

  db:
    build:
      context: web-app
      dockerfile: db.Dockerfile
    image: ecs-demo-db
    hostname: db
    container_name: container-demo-db
    ports:
      - 3307:3306

  sqs:
    container_name: web-app-sqs
    image: softwaremill/elasticmq
    volumes:
      - ./web-app/docker/sqs/custom.conf://opt/elasticmq.conf:ro
    ports:
      - 9325:9324
